apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::812268704080:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-5KFQ7SGFSR2J
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::812268704080:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-15T13:15:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2241"
  uid: 65041e95-4a8e-4ba1-9a7c-263865d51d60
