apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::812268704080:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-Z0QOFUQEDQI5
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::812268704080:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-15T06:33:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1641"
  uid: 75814642-35b0-47e4-881f-d3d62a4cc05f
